"""Add profession and update email to nullable

Revision ID: 5c7953537720
Revises: d414c4fc0881
Create Date: 2025-06-03 03:22:48.446840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c7953537720'
down_revision = 'd414c4fc0881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patronymic', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('profession', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('profession')
        batch_op.drop_column('patronymic')

    # ### end Alembic commands ###
